security:
  oauth2:
    client:
      clientId: 170746790474078
      clientSecret: fc5677843a0b67cb6dd05c19a317307a
      accessTokenUri: https://graph.facebook.com/oauth/access_token
      userAuthorizationUri: https://www.facebook.com/dialog/oauth
      tokenName: oauth_token
      authenticationScheme: query
      clientAuthenticationScheme: form
    resource:
      userInfoUri: https://graph.facebook.com/me